/**
 * Public resonant-code hard-kernel boundary.
 *
 * RCCL lifecycle operations are intentionally available only from
 * `@sovea/resonant-code-core/rccl`.
 */
export { compileChange, evaluateChange } from './runtime/index.ts';

export type {
  AlignmentRequest,
  AttestationPlan,
  ChangeDecisionPacket,
  ChangeEvaluation,
  ChangeException,
  ChangeSet,
  ChangedFile,
  CheckResult,
  CompileChangeInput,
  CompileChangeOutput,
  DecisionDiagnostic,
  DecisionTension,
  DirectiveActivationSummary,
  EffectiveGuidance,
  EvaluateChangeInput,
  EvaluationActionRequired,
  EvaluationBasis,
  EvaluationEvidenceRef,
  EvaluationInformation,
  ExecutionAvoidGuidanceItem,
  ExecutionGuidance,
  ExecutionGuidanceItem,
  FileFact,
  GuidanceAttestation,
  GuidanceDeliverySelection,
  GuidanceDetail,
  GuidanceEvaluation,
  GuidanceItem,
  GuidanceOverflow,
  MachineFactProvenance,
  NormalizedTaskContext,
  RelationProposal,
  ScopeLevel,
  TaskAlignmentReason,
  TaskContextInput,
  TaskDeclaredSource,
  TaskField,
  TaskFieldProvenance,
  TaskFieldSource,
  TaskProvenanceInput,
  TaskRiskLevel,
  VerificationPlan,
  VerificationProposal,
  VerificationRequirement,
  VerificationSource,
} from './runtime/index.ts';
