/** Public deterministic Cognitive Adoption kernel. */
export { compileDelegation } from './delegation/compile.ts';
export { evaluateHandoff } from './handoff/evaluate.ts';

export type {
  AgentInterpretation,
  HumanEvent,
  HumanEventKind,
  InterpretationBasis,
  InterpretationField,
  RepositoryEvidence,
} from './authority/types.ts';
export type {
  ChallengeEvidenceItem,
  ChallengeEvidenceReference,
  ChallengeEvidenceSelection,
  ChallengeIndependence,
  ChallengeOutcome,
  IndependentChallenge,
} from './challenge/types.ts';
export type {
  AdoptionCondition,
  AdoptionConditionInput,
  AdoptionCriticality,
  ChallengePolicy,
  CompactInterpretationBasis,
  CompileDelegationInput,
  DeveloperEventInput,
  DelegationCompileResult,
  DeliveryPlan,
  EvidenceObligation,
  EvidenceObligationFalsification,
  EvidenceObligationInput,
  EvidenceObligationStrategy,
  EvidenceObligationStrategyInput,
  ExactHumanEventInput,
  HostPolicyCapability,
  HostPolicyRequirement,
  HostPolicyRequirementInput,
  LogicalVerifier,
  MaterialDecisionAlternative,
  MaterialDecisionFork,
  MaterialDecisionForkInput,
  MaterializedInterpretation,
  RepositoryEvidenceInput,
  RepositorySelectorKind,
  TaskContract,
  TaskMeaningInput,
  VerificationBaselineInput,
  VerificationDefinition,
  VerificationDefinitionInput,
  VerificationBaselineMode,
  VerificationExpectedStatus,
  VerificationPlan,
  VerificationRevisionInput,
  VerifierRef,
  VerifierRefRole,
} from './delegation/types.ts';
export type {
  ChangedFileFact,
  BaselineCheckFact,
  BaselineVerificationFact,
  CheckBaselineRelation,
  CheckComparisonFact,
  ChangeRepresentation,
  CheckAttemptFact,
  CheckFact,
  CheckEvidenceConcernObservation,
  CheckStepAttemptFact,
  CheckStatus,
  CheckStreamFact,
  EvidenceCause,
  EvidenceConcernSource,
  EvidenceDisposition,
  EvidenceDispositionEntry,
  ExecutableEnvironmentFact,
  ExecutionEnvironment,
  FactBundle,
  FileContentFact,
  FileKind,
  FileOperation,
  LockfileEnvironmentFact,
  PatchFact,
  ToolchainEnvironmentFact,
  VerifierMutation,
  VerificationInputEntryFact,
  VerificationInputSelectorFact,
  VerificationInputSnapshot,
  WorktreeSummary,
} from './facts/types.ts';
export type {
  AdoptionConditionConclusion,
  AgentRecommendation,
  CognitiveHandoff,
  ConclusionStatus,
  DecisionPacket,
  EvidenceObligationConclusion,
  EvaluateHandoffInput,
  HandoffAttentionCode,
  HandoffAttentionItem,
  HandoffAttentionReferences,
  HandoffEvaluation,
  HandoffEvidenceKind,
  HandoffEvidenceReference,
  HandoffStatus,
  HandoffValidationIssue,
  HostPolicyEvaluation,
  HumanDecision,
  HumanDecisionAction,
  HumanDecisionException,
  RecommendationAction,
  ResidualUnknown,
  ReviewQuestion,
} from './handoff/types.ts';
