/** Public deterministic Stetra task kernel. */
export { compileDelegation } from './delegation/compile.ts';
export { evaluateHandoff } from './handoff/evaluate.ts';

export type {
  AgentInterpretation,
  HumanEvent,
  HumanEventKind,
} from './authority/types.ts';
export type {
  AdoptionConcern,
  AdoptionConcernInput,
  Assurance,
  AssuranceInput,
  CheckDefinitionInput,
  CompileDelegationInput,
  ConcernEvidenceRequirement,
  ConcernEvidenceRequirementInput,
  DelegationCompileResult,
  ExactHumanEventInput,
  ExecutionPolicy,
  RepositorySelector,
  RepositorySelectorKind,
  TaskContract,
  TaskInterpretationInput,
  VerificationDefinition,
  VerificationInput,
  VerificationPlan,
  VerifierRef,
  VerifierRefRole,
} from './delegation/types.ts';
export type {
  ChangedFileFact,
  ChangeRepresentation,
  CheckAttemptFact,
  CheckFact,
  CheckStatus,
  CheckStepAttemptFact,
  CheckStreamFact,
  CheckTermination,
  ExecutableEnvironmentFact,
  ExecutionEnvironment,
  FactBundle,
  FileContentFact,
  FileKind,
  FileOperation,
  PatchFact,
  VerificationInputEntryFact,
  VerificationInputSelectorFact,
  VerificationInputSnapshot,
  VerifierMutation,
  WorktreeSummary,
} from './facts/types.ts';
export type {
  AgentRecommendation,
  CognitiveHandoff,
  ConclusionStatus,
  ConcernFinding,
  DecisionPacket,
  EvaluateHandoffInput,
  HandoffAttentionCode,
  HandoffAttentionItem,
  HandoffEvidenceReference,
  HandoffStatus,
  HandoffValidationIssue,
  HandoffEvaluation,
  HumanDecision,
  HumanDecisionAction,
  RecommendationAction,
  ResidualUnknown,
  ReviewFocus,
} from './handoff/types.ts';
