/** Host-native workflow instructions generated by `stetra init`. */

export type HostAdapter = 'codex' | 'claude';

export const HOST_WORKFLOW_REFERENCES = [
  'change', 'delivery', 'challenge', 'handoff', 'recovery',
] as const;
export type HostWorkflowReference = typeof HOST_WORKFLOW_REFERENCES[number];

const CHALLENGER_INSTRUCTIONS = `You are the Stetra Independent Challenger for one bounded Evidence Obligation.

Use only the current Challenge Execution Request and its exact Challenge
Execution Packet. The packet is complete for this bounded role: do not load the
general Stetra skill or its workflow reference pages. Inspect the named target,
exact Human-event basis, current repository, and Runtime evidence, then actively
test the frozen failure hypothesis. Do not broaden the task. If the packet is
structurally insufficient, report partial or unknown instead of recovering
generic workflow context.

You are read-only. Do not edit, format, repair, install, commit, or mutate files.
Do not spawn another agent. Do not choose an implementation route or make the
Human adoption decision. If the available read-only evidence cannot support the
requested observation, return partial or unknown and name the missing evidence.

Return exactly one JSON Challenge Document matching the prefilled
challengeExecutionPacket.draft. Fill only its open judgment fields. Do not wrap
it in Markdown or add prose. Cite only exact IDs present in the packet. Never
author request identity, context identity, independence, or a Host receipt; the
controlling Host owns those fields.`;

export function renderCodexChallengerAgent(): string {
  return `name = "stetra-challenger"
description = "Independently challenge one Stetra evidence obligation in a fresh read-only context."
sandbox_mode = "read-only"
developer_instructions = """
${CHALLENGER_INSTRUCTIONS}
"""
`;
}

export function renderClaudeChallengerAgent(): string {
  return `---
name: stetra-challenger
description: Independently challenge one Stetra evidence obligation in a fresh read-only context.
tools: Read, Grep, Glob
permissionMode: plan
maxTurns: 20
---

${CHALLENGER_INSTRUCTIONS}
`;
}

export function renderHostSkill(adapter: HostAdapter): string {
  const host = adapter === 'codex' ? 'Codex' : 'Claude Code';
  return `---
name: stetra
description: Preserve developer understanding and decision authority while a coding Agent delivers an inspectable change.
---

# Stetra

Use this workflow when a production change needs a complete path from exact
developer intent to an informed adoption decision. ${host} owns investigation,
interpretation, implementation, evidence diagnosis, bounded repair, challenge,
and handoff. The developer owns goals, long-lived tradeoffs, exceptions, and
the final decision. Runtime owns only facts it directly collects.

Read [references/change.md](references/change.md) before prepare. After every
JSON result, follow its structured **hostAction**. If **hostAction.reference**
names a page, ensure that page is available in context; do not reread an
unchanged page already present in one continuous context. Projection changes
instructions, never lifecycle state, authority, evidence, or adoption meaning.
For an **authoringPacket**, fill its pre-bound **draft** using
**fieldRequirements** and **shapeCatalog**, then send it through the exact **inputBinding**.
Requirements define structure, not judgment. Treat
**semanticContext.exactDeveloperEvents** as Human authority and the separately
labeled Agent interpretation as Agent judgment.

Before final response, run **stetra change guard-final . --task
<task-id> --json**. Continue the returned workflow, present its current brief,
or report its recorded Human decision according to **disposition**. This skill
does not claim native Host enforcement.

When **hostAction.developerDecisionBrief** is present, it owns the final
cognitive handoff even if another workflow requests a summary. Follow every
**presentationRequirements** reference, preserve the four decision states,
contrast intended with actual meaning, state that adoption is pending, ask for
the decision, and stop. Never execute **decisionContinuation** before a new
developer message supplies that decision.

Keep Human authority, Agent judgment, Runtime facts, and adoption separate.
Passing evidence is not adoption. Never invent facts, hide Attention, or treat
focus as permission. Preserve paths, IDs, enums, commands, numeric facts,
quoted events, and every adoption-changing surface.
`;
}

export function renderHostWorkflowReference(
  _adapter: HostAdapter,
  workflow: HostWorkflowReference,
): string {
  return WORKFLOW_REFERENCES[workflow];
}

export function renderHostPointerBlock(
  adapter: HostAdapter,
  markers: { start: string; end: string },
): string {
  const skillPath = adapter === 'codex'
    ? '.agents/skills/stetra/SKILL.md'
    : '.claude/skills/stetra/SKILL.md';
  return `${markers.start}
For production coding changes, read and follow [the generated Stetra skill](${skillPath}).
${markers.end}`;
}

export const DELEGATION_PREPARE_EXAMPLE = {
  protocol: 'cognitive-adoption',
  schemaVersion: '1',
  prepareRequestId: 'prepare:host-generated-once',
  developerEvents: [{ key: 'request', content: 'exact developer message', provider: 'host' }],
  repositoryEvidence: [{
    key: 'relevant-source',
    path: 'src/example.ts',
    wholeFile: true,
  }],
  task: {
    basis: { developerEventKeys: ['request'], repositoryEvidenceKeys: [] },
    desiredOutcome: 'observable outcome',
    constraints: [],
    nonGoals: [],
    focus: [],
  },
  materialDecisionForks: [],
  conditions: [{
    key: 'behavior',
    statement: 'what must be true',
    rationale: 'why this changes adoption',
    criticality: 'material',
    basis: { developerEventKeys: ['request'], repositoryEvidenceKeys: ['relevant-source'] },
    evidenceObligations: [{
      key: 'public-path',
      statement: 'bounded conclusion the evidence must support',
      falsification: {
        failureHypothesis: 'plausible wrong implementation to try to exclude',
        scenario: 'specific boundary or counterexample to exercise',
        supportingObservation: 'observation that supports the bounded conclusion',
        contradictingObservation: 'observation that contradicts the bounded conclusion',
      },
      strategies: [
        { kind: 'runtime-check', checkKeys: ['test'] },
        { kind: 'independent-challenge', policy: 'fact-triggered' },
      ],
    }],
  }],
  hostPolicyRequirements: [],
  delivery: { maxRepairAttempts: 2 },
  checks: [{
    key: 'test',
    rationale: 'decision-relevant observation',
    argv: ['package-manager', 'test'],
    baseline: {
      mode: 'task-start',
      rationale: 'why before/after changes this decision',
      expectation: { baselineStatus: 'passed', currentStatus: 'passed' },
      obligationKeys: [{ conditionKey: 'behavior', obligationKey: 'public-path' }],
    },
    verifierSelectors: [
      { kind: 'file', path: 'package.json', role: 'command-definition' },
      { kind: 'tree', path: 'test', role: 'acceptance-surface' },
    ],
  }],
} as const;

const CHANGE_REFERENCE = `# Understand and prepare one change

The fixed path is **prepare -> implement -> collect -> judge evidence ->
resolve/repair/challenge -> handoff -> decide**. Preserve each exact developer
message in **developerEvents**. Keep Host interpretation in **task** and
**conditions**; never blend Host directions into a quoted developer event.
Resolve repository-discoverable facts before asking questions. Another planning
framework may own investigation and clarification; submit its prose as Agent
interpretation, never Human authority.

Send compact initial-version JSON on stdin, never from a file inside the worktree.
Runtime generates event, evidence, condition, obligation, verifier, definition,
plan, and contract IDs:

~~~json
${JSON.stringify(DELEGATION_PREPARE_EXAMPLE)}
~~~

Replace or remove the example Evidence after inspection. Use exact **key/path**
plus **startLine/endLine**, or **wholeFile:true**; Runtime materializes either as
an immutable UTF-8 line window. Checks are shell-free argv. Verifier role is
exactly **command-definition** for invocation definitions or
**acceptance-surface** for artifacts that decide whether the command passes.
Use **task-start** only for a useful initial observation. Exact baselines are
**{"mode":"unknown"}** and
**{"mode":"task-start","rationale":"...","expectation":{"baselineStatus":
"passed|failed|unavailable","currentStatus":"passed|failed|unavailable"},
"obligationKeys":[{"conditionKey":"...","obligationKey":"..."}]}**. Do not
add rationale, expectation, or obligationKeys to unknown. Runtime alerts only
when observations violate that expectation; it never infers a regression. If no command applies,
omit checks and provide a concrete **noCommandRationale**. Routine work may use
an empty conditions array.

Use **materialDecisionForks** only for unresolved or resolved choices that
change desired outcome, explicit constraints, public behavior, compatibility,
ownership, a long-lived tradeoff, external effects, verification relaxation,
or an exception. Local reversible engineering judgment is Agent-owned. If a
fork is unresolved, Runtime creates no task and returns one consolidated
**clarificationBrief**. Present it once and stop. After a new developer message,
append that exact event, bind each resolution to it, update the task basis, and
re-run prepare with the same prepareRequestId. If Trellis or another Host
already completed clarification, submit the resolved forks once; Stetra must
not ask again.

Do not infer importance from paths, keywords, file counts, dependency counts,
diff size, error text, or a scalar score. Every declared condition must contain
falsifiable Evidence Obligations and explicit strategies. Runtime checks
reference logical verifier identities; observations bind exact definitions.

~~~sh
stetra change prepare . --input - --json
~~~

Generate **prepareRequestId** once for this concrete Host request and reuse that
exact value when resolving a pre-task material fork. Reuse the exact input when
retrying an interrupted call after task creation. Runtime returns the
already-published task without rerunning baseline checks. A changed input needs
a new request ID; Runtime never guesses request identity from semantic content.
If another worktree observation still owns the lease, wait for that process to
finish and retry with the same request ID.

Only **prepared** creates a task; **prepare-replayed** returns that same task.
Inspect the returned Task Contract, then follow the exact
**hostAction.command.argv**.
`;

const DELIVERY_REFERENCE = `# Implement, collect, and judge evidence

Implement inside the compiled task meaning. Local reversible engineering
choices are Agent-owned; stop when a long-lived semantic choice or an external
or irreversible effect crosses the escalation boundary.

Prepare runs only checks explicitly marked **task-start**, records any changes
they cause, and freezes the post-check worktree as the implementation baseline.
Collect captures the full baseline-to-current change, current check attempts,
mechanical baseline/current relations, check-induced changes, verifier
mutations, bounded logs with full-stream digests, and non-secret environment
identity. Direct Host execution does not replace Runtime facts.

Inspect the complete patch and every non-passing check. Submit one evidence
disposition covering each current non-passing check exactly once:

~~~json
{
  "semanticImpact":"none",
  "proposedRoute":"repair-implementation",
  "routeRationale":"why this next step addresses every declared cause",
  "entries":[{
    "source":{"kind":"check","definitionId":"definition id prefilled by hostAction.authoringPacket"},
    "cause":"implementation",
    "diagnosis":"fact-bound cause judgment",
    "falsificationAttempt":"what was inspected or tried",
    "codeChangeCanAlterObservation":true,
    "expectedDifferentObservation":"specific next Runtime observation",
    "intendedChanges":["bounded intended edit"]
  }]
}
~~~

~~~sh
stetra change diagnose . --task <task-id> --input - --json
~~~

Cause is exactly **implementation/environment/verification/unknown**. Choose
**proposedRoute** explicitly and explain it in **routeRationale**. These are
Agent judgments, not Runtime facts. Runtime validates current references,
coverage, and cause/route compatibility only; it does not inspect error text to
choose a route. Implementation can repair or hand off. Environment and
verification can revise the immutable Verification Plan or hand off. Unknown
can challenge, hand off, or ask the developer. Material semantic impact must
ask the developer. Repair-budget exhaustion mechanically changes an otherwise
valid repair route to handoff while preserving the proposal. Do not propose
code changes for another cause. Mechanical verification relaxation requires
exact Human authority.
The returned **fieldRequirements** names every enum choice and references
reusable object variants through **shapeCatalog**; do not infer a default from
the ordering.
`;

const CHALLENGE_REFERENCE = `# Challenge a falsifiable Evidence Obligation

When **hostAction.challengeExecutionRequest** is present, dispatch exactly its
**stetra-challenger** profile in one fresh Host context. Do not perform the
Challenge in the Implementer context and do not substitute another Agent role.
The request binds the task, effective contract, Attempt, fact collection, and
exact Challenge Execution Packet fingerprint; it forbids mutation and parallel
fan-out.
This happens for an explicitly required obligation and when a **fact-triggered**
obligation relies on a verifier acceptance surface changed by the patch. The
route uses only explicit obligation/verifier/mutation relationships. Never infer
it from filenames, test names, error text, or diff shape.

Pass **hostAction.challengeExecutionPacket** to that fresh context. It contains
exactly one target Condition and Evidence Obligation, only their exact
Human-event basis, only explicitly related Checks, Repository Evidence, and
Verifier mutations, plus a compact list of every changed file and one Patch
reference. Declared relations come only from frozen IDs, selectors, and exact
repository-evidence paths; they are not relevance guesses. The packet is
self-contained for this role. Do not ask the Challenger to load the general
Stetra skill or workflow references.

Start from **challengeExecutionPacket.draft**. Its changedFiles, checks,
repositoryEvidence, and humanEvents are canonical identities, not paths or
display labels. Preserve its obligation IDs, falsification design, and evidence
selection exactly. Use **output.allowedOutcomes** and
**output.evidenceItemShape** for the open Agent-judgment fields.

~~~json
{
  "obligationIds":["obligation id prefilled by challengeExecutionPacket"],
  "falsification":{"failureHypothesis":"concrete way the conclusion could be wrong","scenario":"specific boundary to exercise","supportingObservation":"result supporting the conclusion","contradictingObservation":"result contradicting the conclusion"},
  "evidence":{"changedFiles":["changed-file id"],"checks":["definition id"],"repositoryEvidence":[],"humanEvents":["event id"],"patch":true},
  "falsificationAttempt":"what was inspected or executed",
  "observedResult":"what the independent attempt actually observed",
  "supportingEvidence":[{"statement":"bounded support","references":[{"kind":"check","id":"definition id"}]}],
  "counterEvidence":[],
  "outcome":"supported","conclusion":"bounded conclusion"
}
~~~

Challenge output remains Agent judgment. Independence and context identities
are injected only by a trusted Host integration; Agent JSON cannot claim them.
The Challenger returns only the JSON Challenge Document. The Host wraps that
output as **{requestId, hostReceipt, challenge}**, and only the Host fills the
receipt after it observed both lifecycle boundaries and bound the exact output
fingerprint. Send that complete **hostChallengeSubmission** through the returned
command. Without a trusted receipt, a thin Host still runs the generated
Challenger profile and submits **{challenge}**. It must not manufacture a
receipt: Runtime records the result as **unverified**, prevents it from
supporting a required obligation, and adds direct Human review. Partial,
contradicted, unknown, or
missing required challenge caps the related obligation conclusion. A partial,
contradicted, or unknown Challenge returns to the Implementer through the
normal evidence-diagnosis packet. Diagnose its exact Challenge source and
choose bounded repair, verification revision, Human resolution, or Handoff;
do not send the same adverse finding to another Challenger.
`;

const HANDOFF_REFERENCE = `# Author the Cognitive Handoff and obtain a Human decision

After inspecting the complete current change, checks, Attempt lineage,
diagnoses, and Challenges, submit a handoff on stdin. Runtime injects contract,
Attempt, fact-collection, and fingerprint identities; do not author machine facts.

Fill the exact **hostAction.authoringPacket.draft**; it already contains current
immutable IDs and outstanding obligations. **fieldRequirements** lists the
allowed conclusion/recommendation values; each **shapeRef** resolves to one
reusable variant set in **shapeCatalog** without selecting an answer. The handoff contains a decision
summary, exactly one conclusion per Evidence Obligation and condition,
important system effects, residual unknowns,
consequence-directed review questions, and an Agent recommendation. Evidence is
an array of exact references such as **{"kind":"check","id":"..."}** or
**{"kind":"patch"}**. Every Obligation conclusion states the concrete
falsification attempt and its observed result against the frozen scenario. Do
not repeat Runtime facts as Agent prose or create one review item per changed
file. Recommend **accept** only when every Condition and Obligation is
supported, every required Challenge is trusted and favorable, checks pass, and
no adoption-changing unknown, required Host-policy gap, exhausted repair, or
unrepresentable change remains. Otherwise use request-correction, defer, or
reject; only a later exact Human decision may accept exceptions.

For every input-bearing action, serialize the completed draft and provide those
bytes as stdin to the exact argv in one process. A Host API should bind stdin
directly. If it cannot, use a temporary input outside the project worktree and
delete it after the command; never add task-authoring files to the repository.

~~~sh
stetra change handoff . --task <task-id> --input - --json
~~~

The returned **hostAction.developerDecisionBrief** is the delivery surface for
the developer. It distinguishes delivery state, evidence state, Agent
recommendation, and Human adoption; contrasts desired outcome with actual
system meaning; preserves every condition conclusion; and turns each exact
Attention cause into a decision issue with its relevant review questions.
Causes with the same exact group and references share one issue while retaining
all underlying Attention IDs, codes, and resolutions. Prior evidence diagnosis
and recovery routes remain visible in **evidenceHistory**.
Present that brief as the final task summary even when another active workflow
has its own completion template. Do not collapse, rename, or omit any item named
by **presentationRequirements**. Compact Runtime evidence is supporting detail,
not the lead. Full
contracts, Attempt history, challenges, handoff, and events remain available
through the named **detailSections**. **handoff-ready** means structurally ready for a
Human decision, never adopted. **needs-attention** preserves unresolved facts
or conclusions as direct-cause decision issues.

Immediately before presenting it, run the read-only **change guard-final**
command. Present only the current brief returned by that guard; if facts became
stale or another action is pending, follow the guard's hostAction first.

State that adoption is pending, ask the developer to accept, request a
correction, reject, or defer, and stop. Do not execute
**hostAction.decisionContinuation** in the same turn. After a new developer
response arrives, copy its Authoring Packet draft, preserve the exact message,
and submit it with the nested command and input binding:

~~~json
{
  "humanEvent":{"content":"exact developer message","provider":"host"},
  "action":"accepted",
  "reason":"normalized reason tied to the exact message",
  "exceptions":[]
}
~~~

Actions are **accepted/correction-requested/rejected/deferred**. Acceptance with
Attention requires an explicit exception naming every Attention ID. Decide
never commits, merges, publishes, deploys, or activates a cross-task rule.
`;

const RECOVERY_REFERENCE = `# Recover without hiding evidence

Follow **hostAction.kind** exactly:

- **retry-timed-out-check**: keep the worktree unchanged and run the returned
  larger-budget retry; every earlier attempt remains visible.
- **diagnose-collected-evidence**: classify every non-passing fact and submit a
  falsifiable evidence disposition. Do not assume repair.
- **revise-verification**: fill the projected revision draft. Logical verifier
  identity remains stable; exact definitions gain a revision and supersedes
  link. Kind is exactly **execution-rebinding** or **verification-plan**. The
  packet lists both accepted baseline shapes. Never claim an original baseline
  was observed in the modified worktree.
- **recollect-stale-facts**: post-collection edits invalidated current facts;
  collect again before semantic evaluation.
- **resolve-evidence-decision**: preserve facts and diagnosis, fill the returned
  resolution Authoring Packet, and run its exact **change resolve** command.
- **correct-protocol-input/configure-verification/resolve-human-choice**:
  correct only the named missing authority or evidence input.

Non-passing checks, baseline expectation mismatches, verifier mutations,
check-induced changes, unrepresentable changes, adverse conditions, challenge
independence, residual unknowns, and exhausted delivery remain exact Attention.
They may add review obligations but never become a score or automatic rejection.

Use **stetra change explain . --task <task-id> --section
contract|baseline|plan|attempts|challenge|revision|handoff|decision|events --json** for exact
artifacts. Supplemental Host probes remain labeled Agent evidence.
`;

const WORKFLOW_REFERENCES: Record<HostWorkflowReference, string> = {
  change: CHANGE_REFERENCE,
  delivery: DELIVERY_REFERENCE,
  challenge: CHALLENGE_REFERENCE,
  handoff: HANDOFF_REFERENCE,
  recovery: RECOVERY_REFERENCE,
};
