/** Host-native instructions generated by `resonant-code init`. */

export type HostAdapter = 'codex' | 'claude';

export const HOST_WORKFLOW_REFERENCES = [
  'change',
  'context',
  'setup',
] as const;
export type HostWorkflowReference = typeof HOST_WORKFLOW_REFERENCES[number];

export function renderHostSkill(adapter: HostAdapter): string {
  const hostName = adapter === 'codex' ? 'Codex' : 'Claude Code';
  return `---
name: resonant-code
description: "Use the resonant-code CLI for concrete coding changes and explicit resonant-code setup, readiness, or decision-relevant repository-context calibration performed with ${hostName}. Do not use it for general repository questions or standalone code review."
---

# Resonant Code

Use this skill as a thin router. The CLI is the deterministic control plane and
never calls a model. Retain semantic task understanding and repository
inspection; do not recreate Runtime or RCCL policy in this skill.

## Route

- For implementation, bug fixes, features, refactors, migrations, tests, and
  other concrete repository changes, read \`references/change.md\` completely.
- For explicit installation, readiness, checks configuration, or Team Playbook
  setup, read \`references/setup.md\` completely.
- For explicit creation or refresh of durable decision-relevant repository
  observations, read \`references/context.md\` completely.
- Standalone code review is not a supported workflow yet. Keep review read-only
  and do not turn it into a change without explicit user authorization.

Read only the workflow reference needed for the current request.

## Collaboration boundary

Proceed without interrupting the user for repository-discoverable task fields,
optional-guidance selection, use of already-approved RCCL, implementation
inside the requested scope, configured checks, and evidence-backed
attestations.

Inform the user without blocking for absent optional Team Playbook, RCCL,
personal overlay, or feedback history.

Pause for user direction before changing persistent team authority or trusted
configuration, approving an RCCL observation or policy exception, resolving a
task-intent ambiguity or policy tension, expanding scope, or accepting an
unresolved failed check, hard violation, or high-risk unverified outcome.
Never claim that an agent-generated approval came from a human.

## Shared boundaries

- Use \`--json\` for every Host invocation.
- Do not parse or merge Playbook policy outside Runtime.
- Do not infer semantic relations from token overlap.
- Do not invent changed files or check outcomes.
- Evaluate only guidance delivered by the prepared decision.
`;
}

export function renderHostWorkflowReference(
  adapter: HostAdapter,
  workflow: HostWorkflowReference,
): string {
  if (workflow === 'change') return renderChangeReference(adapter);
  if (workflow === 'context') return renderContextReference();
  return renderSetupReference();
}

export function renderHostPointerBlock(
  adapter: HostAdapter,
  markers: { start: string; end: string },
): string {
  const skillPath = adapter === 'codex'
    ? '.agents/skills/resonant-code/SKILL.md'
    : '.claude/skills/resonant-code/SKILL.md';
  return [
    markers.start,
    `For concrete coding changes or explicit resonant-code setup/context work, read and follow \`${skillPath}\`.`,
    'Use the `resonant-code` CLI as the deterministic change-harness control plane.',
    markers.end,
  ].join('\n');
}

function renderChangeReference(adapter: HostAdapter): string {
  const hostName = adapter === 'codex' ? 'Codex' : 'Claude Code';
  return `# Change workflow

Use this workflow only for a concrete coding change authorized by the user.
${hostName} owns task semantics, implementation, and semantic attestations.
The CLI owns policy compilation, the worktree baseline, check execution, and
evaluation facts.

## Prepare

Run before editing:

\`\`\`sh
resonant-code change prepare . \\
  --task "<concrete task>" \\
  --change-type <bugfix|feature|refactor|migration|maintenance|docs|test|unknown> \\
  --target <repository-path> \\
  --json
\`\`\`

Add repeatable \`--target\`, \`--tech\`, \`--constraint\`, \`--avoid\`, or
\`--uncertainty\` only when they are material. Use \`--risk\`, \`--scope\`, or
\`--mode strict\` when the request or repository makes them meaningful.

Handle results as follows:

- \`needs-interpretation\`: resolve repository-discoverable fields yourself;
  pause only when the missing information is a user-intent decision.
- \`guidance-overflow\` with mandatory guidance within budget: select only
  task-relevant optional IDs, write
  \`{ "considerIds": [...], "rationale": "..." }\`, and rerun with
  \`--selection-file\`. Do not ask the user merely to rank optional advice.
- \`guidance-overflow\` with mandatory guidance over budget: pause for a scope,
  policy, or explicitly larger-budget decision.
- Missing checks in \`checkPlan\`: read \`setup.md\`, propose exact commands,
  obtain approval, configure them, and rerun prepare before editing.
- A returned session path authorizes implementation under the delivered
  required, avoid, tension, and consider sections.

The workflow automatically loads existing Team Playbook, personal overlay, and
RCCL sources. Do not recalibrate RCCL for every task.

If a current reviewed RCCL observation has a material semantic relationship to
an active directive, provide a bounded relation file only after inspecting the
observation and its exact evidence:

\`\`\`json
{
  "relations": [
    {
      "directiveId": "directive-id",
      "observationId": "observation-id",
      "relation": "supports",
      "rationale": "Concrete task-specific semantic relationship.",
      "evidenceRefs": ["src/example.ts:10-24"]
    }
  ]
}
\`\`\`

Allowed relations are \`supports\`, \`conflicts\`, and \`limits\`. Runtime, not
the Host, decides whether a proposal can affect execution.

## Implement

Stay within the requested scope and the prepared baseline. Follow only the
delivered guidance as normative task guidance. If implementation reveals a
durable missing repository boundary, finish the authorized change unless that
boundary makes the current work unsafe; suggest context calibration separately.

## Complete

Write semantic attestations and user-approved exceptions only:

\`\`\`json
{
  "attestations": [
    {
      "guidanceId": "delivered-guidance-id",
      "verdict": "satisfied",
      "attestedBy": "coding-agent",
      "explanation": "Concrete explanation tied to the actual change.",
      "evidenceRefs": [
        {
          "kind": "diff",
          "ref": "diff:src/example.ts",
          "file": "src/example.ts"
        }
      ]
    }
  ],
  "exceptions": []
}
\`\`\`

Evidence kinds are \`diff\`, \`file\`, \`check\`, and \`semantic\`. Diff/file
evidence must name a collected changed file, check evidence must name a
collected passing check, and semantic evidence needs a concrete description.
Never add \`changes\`, \`checks\`, or declared pass/fail outcomes to this file.

An exception may be marked \`approved\` only after the user reviews its exact
guidance ID and reason. Do not invent \`approvedBy\`.

\`\`\`sh
resonant-code change complete \\
  --session <prepare-session-path> \\
  --evaluation-file <evaluation.json> \\
  --json
\`\`\`

Report changed-file counts, check outcomes, guidance verdicts, exceptions, and
remaining review needs. Fix in-scope failures and rerun completion when safe;
pause for unresolved failures, hard violations, exceptions, or scope changes.
`;
}

function renderSetupReference(): string {
  return `# Setup and readiness workflow

Use this workflow only when the user explicitly asks to install, configure, or
inspect resonant-code readiness.

## Inspect

\`\`\`sh
resonant-code status . --json
resonant-code doctor . --strict --json
\`\`\`

Treat readiness levels differently:

- Required issues block trusted operation and must be resolved.
- Recommended items improve repository-specific guidance but do not block.
- Optional items such as RCCL and feedback history are not setup requirements.

## Configure checks

When \`.resonant-code/checks.json\` is absent or invalid:

1. Inspect repository-owned scripts, CI definitions, and developer
   documentation with normal Host tools.
2. Propose the smallest explicit set of trusted commands. Do not guess from
   filenames or dependency presence alone.
3. Show the user every command argv and timeout. Pause for approval because
   this file defines commands the harness will execute.
4. After approval, write:

\`\`\`json
{
  "version": "1.0",
  "checks": [
    {
      "id": "typecheck",
      "command": ["corepack", "pnpm", "typecheck"],
      "timeoutMs": 120000
    }
  ]
}
\`\`\`

Commands are argv arrays and never shell strings. Run \`doctor --strict --json\`
after writing the file. Do not claim readiness while a required issue remains.

## Optional Team Playbook

Built-in guidance works without a local augment. When the user wants
repository-specific Playbook layers, run:

\`\`\`sh
resonant-code bootstrap prepare . --json
\`\`\`

Inspect the repository, choose only concretely supported layers, and create the
candidate requested by the prepare contract. Before
\`resonant-code bootstrap commit\`, show the user the selected layers, exact
repository evidence paths, rationale, and destination file. Commit only after
approval because the resulting Team Playbook affects future tasks.

Do not calibrate RCCL as a generic setup step. Use \`context.md\` only for a
specific durable repository boundary whose omission could worsen a future
implementation or review decision.

## Generated artifacts

Do not hand-edit generated skill files or marked blocks. Refresh them with
\`resonant-code init .\`; use \`--force\` only after the user confirms that a
modified managed artifact may be replaced.
`;
}

function renderContextReference(): string {
  return `# Repository-context workflow

RCCL is optional and is not a repository summary. Use this workflow only when a
durable observation about compatibility, public API shape, architecture,
data-flow, migration, module format, testing, error handling, or review focus
could prevent a different and worse future decision.

Do not store versions, file lists, exported-symbol inventories, generic style,
or facts tools can cheaply rediscover. Prefer no observation over a weak one.

## Prepare a bounded contract

Select exact source windows with normal Host tools:

\`\`\`sh
resonant-code context prepare . \\
  --evidence <repository-file>:<start>-<end> \\
  --json
\`\`\`

The CLI returns immutable window IDs, exact snippets, a contract fingerprint,
and the proposal schema. Propose observations only against those window IDs.

\`\`\`yaml
schemaVersion: "1.0"
requestId: "<from-prepare>"
contextFingerprint: "<from-prepare>"
replace: false
observations:
  - id: "obs-public-api-boundary"
    category: "architecture"
    scope: "src/api/**"
    statement: "Public API construction is centralized in src/api/index.ts."
    affects: ["api-shape", "architecture-boundary"]
    decisionImpact: "A second entrypoint would split the supported public API."
    semanticConfidence: "high"
    evidence:
      - windowId: "window:<from-contract>"
\`\`\`

## Persist a generated candidate

Before writing, show the user each statement, decision impact, confidence,
scope, and exact evidence window. After authorization to persist the candidate:

\`\`\`sh
resonant-code context commit . \\
  --contract <prepare.json> \\
  --input <proposal.yaml> \\
  --json
\`\`\`

Committed observations remain generated and cannot change directive execution.

## Approve independently

Show the stored observation and its current
\`lifecycle.contentFingerprint\` to the reviewer. Only after explicit review,
run:

\`\`\`sh
resonant-code context approve . \\
  --id <observation-id> \\
  --fingerprint <observation-id>=<content-fingerprint> \\
  --approved-by <reviewer> \\
  --json
\`\`\`

Never approve an observation merely because its snippet still matches, and
never attribute approval to a human who did not provide it. A fingerprint
mismatch means the content changed and must be reviewed again.

Use \`context validate\` for a read-only evidence check and
\`context refresh-stale\` to persist evidence lifecycle changes. Evidence
currency does not create semantic approval.
`;
}
