/** Host-native workflow instructions generated by `resonant-code init`. */

export type HostAdapter = 'codex' | 'claude';

export const HOST_WORKFLOW_REFERENCES = ['change'] as const;
export type HostWorkflowReference = typeof HOST_WORKFLOW_REFERENCES[number];

export function renderHostSkill(adapter: HostAdapter): string {
  const host = adapter === 'codex' ? 'Codex' : 'Claude Code';
  return `---
name: resonant-code
description: Run an authority-visible, fact-bound Semantic Handoff for production coding changes.
---

# resonant-code

Use this workflow for production coding changes where a developer needs an
inspectable model of the actual change before deciding whether to adopt it.

${host} owns investigation, interpretation, implementation, falsification,
and repair. Humans own goals, long-lived tradeoffs, exceptions, and adoption.
Runtime owns only collected Git and check facts. Never relabel Agent judgment
as a Human Event or Runtime fact.

Read [references/change.md](references/change.md) completely before preparing
a change. Invoke every lifecycle command with \`--json\`. The CLI never calls
an LLM.
`;
}

export function renderHostWorkflowReference(
  _adapter: HostAdapter,
  workflow: HostWorkflowReference,
): string {
  if (workflow !== 'change') throw new Error(`Unsupported Host workflow: ${workflow}`);
  return CHANGE_REFERENCE;
}

export function renderHostPointerBlock(
  adapter: HostAdapter,
  markers: { start: string; end: string },
): string {
  const skillPath = adapter === 'codex'
    ? '.agents/skills/resonant-code/SKILL.md'
    : '.claude/skills/resonant-code/SKILL.md';
  return `${markers.start}
For production coding changes, read and follow [the generated resonant-code skill](${skillPath}).
${markers.end}`;
}

const CHANGE_REFERENCE = `# Semantic Handoff change workflow

## Authority and autonomy

- Preserve exact user messages and explicit decisions as Human Events.
- Structured outcomes, constraints, focus, consequence, claims, and
  recommendations remain Agent interpretations with exact event/evidence
  references.
- Resolve repository facts yourself. Ask one consolidated question only when
  viable choices differ on public behavior, compatibility, ownership,
  irreversible migration, security/reliability burden, or another long-lived
  human-owned tradeoff.
- The task authorizes necessary local reversible investigation, edits, checks,
  diagnosis, and repair. Focus paths are not write permissions.
- Do not prepare while a material semantic fork remains.

The normal path is exactly \`prepare -> collect -> finalize\`. Repeat collect
after a repair. Explain is an on-demand inspection command, not a normal final
step.

## 1. Prepare the Semantic Contract

Send the JSON on stdin with \`--input -\`. Never store this transient task
input inside the project worktree.

\`\`\`json
{
  "protocol": "semantic-delegation",
  "schemaVersion": "1",
  "humanEvents": [
    {
      "id": "event:task",
      "kind": "task",
      "content": "exact human message",
      "provider": "host name",
      "nativeId": "optional native event id"
    }
  ],
  "repositoryEvidence": [],
  "semantic": {
    "desiredOutcome": {
      "value": "concrete requested outcome",
      "basis": {"humanEventIds": ["event:task"], "repositoryEvidenceIds": []}
    },
    "constraints": [],
    "nonGoals": [],
    "focus": [],
    "consequence": {
      "value": "medium",
      "basis": {"humanEventIds": ["event:task"], "repositoryEvidenceIds": []}
    },
    "assuranceDimensions": [
      {
        "dimension": "behavior",
        "criticality": "material",
        "rationale": "The requested behavior is the bounded adoption decision surface.",
        "basis": {"humanEventIds": ["event:task"], "repositoryEvidenceIds": []}
      }
    ]
  },
  "verification": {
    "checks": [
      {
        "id": "test",
        "rationale": "requested behavior or regression boundary",
        "argv": ["package-manager", "test"],
        "timeoutMs": 120000,
        "source": "host-task",
        "commandDefinitionPaths": ["package.json"],
        "acceptanceSurfacePaths": ["test/public.test.ts"]
      }
    ]
  }
}
\`\`\`

Each semantic value contains \`value\` and \`basis\`; Runtime generates the
interpretation identity. Consequence describes the adoption impact if the
change or its explanation is wrong, not implementation effort, diff size, or
file count:

- low: a bounded, reversible change with no material compatibility, ownership,
  migration, security, recovery, or long-lived decision consequence;
- medium: adoption depends on at least one explicit material dimension;
- high: adoption depends on at least one explicit adoption-critical dimension.

\`assuranceDimensions\` is empty only for low-consequence routine work. Medium
work declares at least one material or adoption-critical dimension. High work
declares at least one adoption-critical dimension. Use only dimensions that can
change adoption or direct review; do not manufacture coverage. Runtime compiles
an inspectable routine, standard, or critical \`assurancePlan\`. A critical
dimension can escalate a low/medium label; no score or repository heuristic can
downgrade it.

Evidence windows contain \`id\`, repository-relative \`path\`, \`startLine\`,
and \`endLine\`; matching proves currency, not truth.

Checks use argv arrays without a shell. If no executable check applies, replace
\`checks\` with a concrete \`noCommandRationale\`. Declare command-definition
and acceptance-surface paths separately; use empty arrays when neither exists.
Prepare resolves only the top-level executable; nested modules, services, and
runtime prerequisites remain collect-time facts.

Run the command with the document on stdin:

\`\`\`sh
resonant-code change prepare . --input - --json
\`\`\`

Inspect the returned \`semanticContract\`, especially its exact
\`assurancePlan.requirements\`. Non-runnable results create no run; correct the
exact issue without bypassing it.

## 2. Implement and collect facts

Implement and safely repair inside the compiled contract. Re-align only if the
discovered work changes a long-lived semantic value. Then run:

\`\`\`sh
resonant-code change collect . --run <run-id> --json
\`\`\`

Inspect every returned changed path, check outcome, changed verifier surface,
the returned \`assurancePlan\`, and the complete patch at \`patch.path\`.
Runtime, not Host prose, owns those facts. If repair is needed, edit and collect
again; recollection replaces the old facts and resets \`handoff.json\`.

## 3. Author the Cognitive Handoff

Fill the returned \`handoffPath\`. Select only changed paths and check IDs from
the current collect packet. Do not declare collection identity, operations,
check results, patch content, confidence, or adoption.

\`\`\`json
{
  "protocol": "semantic-delegation",
  "schemaVersion": "1",
  "systemMeaningUpdate": "compact description of the implemented system",
  "materialClaims": [
    {
      "id": "claim:behavior",
      "dimension": "behavior",
      "statement": "concrete adoption-relevant conclusion",
      "adoptionConsequence": "what accepting this conclusion changes",
      "adoptionCritical": false,
      "basis": "agent-judgment",
      "evidence": {
        "changedFiles": ["exact/path.ts"],
        "checks": ["test"],
        "patch": true
      }
    }
  ],
  "residualUnknowns": [],
  "reviewMap": []
}
\`\`\`

For a routine plan with no required dimension, keep \`materialClaims\` empty
unless the actual change exposes a material conclusion. For every compiled
requirement, provide at least one claim with the same dimension. A compiled
adoption-critical requirement must be covered by an adoption-critical claim.
Do not add claims merely to restate changed files, checks, or the requested
outcome.

Use an empty \`residualUnknowns\` array when none remains and an empty
\`reviewMap\` when neither the Assurance Plan nor collected facts require direct
review. Claim dimensions are behavior, invariant, state-ownership, data-flow,
control-flow, compatibility, migration, failure-recovery, security, operations,
maintenance, and important-non-change. Bases are repository-evidence,
agent-judgment, human-decision, and unverified. A passing check supports Agent
judgment; it does not create a Runtime semantic fact.

Every adoption-critical Agent/repository/unverified claim requires
falsification. Inspect the complete patch and actively seek counterevidence.
Use supported, contradicted, partial, or unverified; never hide counterevidence.
Non-critical claims must omit falsification. Every adoption-critical claim,
including a newly discovered Host escalation, requires must-read or unresolved
Review Map coverage even when supported. Also cover unknowns, failed/unavailable
checks, changed verifier surfaces, and unrepresentable files there.
Attention explains adoption impact, exact evidence, and a concrete action. The
Review Map only orders inspection surfaces and never substitutes for attention.
A passing happy path alone is not a falsification attempt.

When needed, use these exact nested shapes:

- falsification: \`{"failureHypothesis":"...","attempt":"...","status":"unverified","supportingEvidence":{},"counterEvidence":{},"conclusion":"..."}\` (or use supported, contradicted, or partial with the evidence each result requires);
- residual unknown: \`{"id":"unknown:id","statement":"...","adoptionImpact":"...","validationPath":"...","references":{"claims":[],"changedFiles":[]}}\`;
- Review Map entry: \`{"id":"review:id","priority":"must-read|useful-to-sample|mechanically-covered|unresolved","changedFiles":[],"checkIds":[],"claimIds":[],"unknownIds":[],"rationale":"...","prevents":"..."}\`.

Choose challenge depth by the actual dimension:

- state ownership: trace every writer, coupled field, early return, failure,
  execution order, repeated operation, and later participant;
- control flow: trace every material branch, cleanup, callback, and async
  timing boundary;
- compatibility: probe the promised scope at the generic implementation owner
  across applicable environments and preserved inputs/state;
- failure/recovery: force partial execution, retry, duplicate invocation,
  rollback, cleanup, and idempotency boundaries.

## 4. Finalize and hand off

\`\`\`sh
resonant-code change finalize . --run <run-id> --json
\`\`\`

Repository edits after collect return \`facts-stale\`. Failed checks or a
contradicted critical claim reject. Missing evidence, changed verifier
surfaces, residual unknowns, and partial/unverified critical claims need
attention. \`handoff-ready\` means ready for human review, never adopted.

For a completed result, return \`presentationMarkdown\` to the developer
unchanged. It is the CLI-owned authority partition. If supplemental Host-only
probes materially help, append them under a separate **Agent supplemental
evidence** heading; never add them to Runtime facts.

Only when exact underlying detail is needed, use one of:

\`\`\`sh
resonant-code change explain . --run <run-id> --section contract --json
resonant-code change explain . --run <run-id> --section facts --json
resonant-code change explain . --run <run-id> --section handoff --json
resonant-code change explain . --run <run-id> --section evaluation --json
resonant-code change explain . --run <run-id> --section presentation --json
\`\`\`
`;
